### ISSUE TITLE
No data in show

### ISSUE THREAD

**Issue by Rohlik** [mlabouardy/dockerswarm-ui#3]
Hello again,
after successful build I see only this - just menu without data.
I try run container with environment DOCKER_HOST and without it, result is same.

![screen](https://cloud.githubusercontent.com/assets/2051154/13807130/f571521e-eb5f-11e5-9559-98c47a690c5c.png)

**Comment by mlabouardy** [comment]
can you give me the command line that you used to run the container :)

**Comment by mlabouardy** [comment]
its better to use the stable image on docker hub:

docker run -d -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock --name dockerswarm-ui mlabouardy/dockerswarm-ui:1.0.0

or 

docker run -d -p 3000:3000 -e DOCKER_HOST=tcp://IP:2375 --name dockerswarm-ui mlabouardy/dockerswarm-ui:1.0.0

**Comment by Rohlik** [comment]
Works great now. Thx you so much for help me with my problem.
PS: I love your simple design of web ui.
PSS: My _nodes_ tab is empty, it's OK or it's bug? Everything else works.
PSSS: I try on my another Swarm cluster and _nodes_ tab have correct data. I guess, this is problem with my Swarm configuration. Your app don't correct parse data from Swarm when I using Swarm and his function replication. Look at my screen:
![swarm](https://cloud.githubusercontent.com/assets/2051154/13840697/57d4cda4-ec24-11e5-8102-09112b537bca.png)
