### ISSUE TITLE
Only 1 out of 3 nodes

### ISSUE THREAD

**Issue by rcardenal** [mlabouardy/dockerswarm-ui#4]
Hi,

swarm at 172.26.10.193, nodes at same subnet, 190-191-192.

From command line:

$ docker -H :4000 info
Containers: 32
 Running: 12
 Paused: 0
 Stopped: 20
Images: 211
Server Version: swarm/1.2.0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 3
 docker01: 172.26.10.190:2375
  └ Status: Healthy
  └ Containers: 11
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.958 GiB
  └ Labels: executiondriver=, kernelversion=3.16.0-4-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-22T07:54:13Z
  └ ServerVersion: 1.11.0
 docker02: 172.26.10.191:2375
  └ Status: Healthy
  └ Containers: 11
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.958 GiB
  └ Labels: executiondriver=, kernelversion=3.16.0-4-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-22T07:54:20Z
  └ ServerVersion: 1.11.0
 docker03: 172.26.10.192:2375
  └ Status: Healthy
  └ Containers: 10
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.958 GiB
  └ Labels: executiondriver=, kernelversion=3.16.0-4-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-22T07:54:08Z
  └ ServerVersion: 1.11.0
Plugins:
 Volume:
 Network:
Kernel Version: 3.16.0-4-amd64
Operating System: linux
Architecture: amd64
CPUs: 3
Total Memory: 11.88 GiB
Name: dc700e65f50d
Docker Root Dir:
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support

Launched the image as:

docker run -d -p 3000:3000 -e DOCKER_HOST=tcp://172.26.10.193:4000 --name dockerswarm-ui mlabouardy/dockerswarm-ui

But in nodes view:

![instantanea191](https://cloud.githubusercontent.com/assets/8673000/14735844/a7bf38fc-0873-11e6-9d13-87b05f5d0239.png)

Any thoughts?

Thanks!

Rubén.

**Comment by mlabouardy** [comment]
hello, can you give me more information about your docker and docker swarm version :+1:

**Comment by rcardenal** [comment]
Well, you can see that info in the OP for the swarm node and the remote nodes :)

Server Version: swarm/1.2.0

docker01: 172.26.10.190:2375
└ ServerVersion: 1.11.0
docker02: 172.26.10.191:2375
└ ServerVersion: 1.11.0
docker03: 172.26.10.192:2375
└ ServerVersion: 1.11.0

**Comment by yun1981** [comment]
I had the similar problem too.

![image](https://cloud.githubusercontent.com/assets/15043876/15309992/768ffa5a-1c1e-11e6-9c34-7d465fb22593.png)
![image](https://cloud.githubusercontent.com/assets/15043876/15310003/975778f8-1c1e-11e6-8634-3d3f81cfa479.png)

**Comment by dnorth98** [comment]
First off, this project is potentially awesome!!  I love the design

I've got the same problem as @yun1981 though in that the nodes screen looks all messed up.

docker v 1.11.1
swarm/1.2.2

**Comment by mlabouardy** [comment]
@dnorth98  @rcardenal  @yun1981  I have just fixed, thanks for your feedback guys :+1:
